### ISSUE TITLE
Add state machine to proposal model

### ISSUE THREAD

**Issue by timbuchwaldt** [timbuchwaldt/einbeiniger#5]
States:
created, accepted, rejected, backup (accepted, but show seems full. if someone can't attend, be prepared)

**Comment by klaustopher** [comment]
Suggestion: [workflow](https://github.com/ryan-allen/workflow) ... Used it at work quite often ... small & nice ;)

**Comment by timbuchwaldt** [comment]
Already used aasm now, works :)

**Comment by klaustopher** [comment]
:thumbsup:

**Comment by timbuchwaldt** [comment]
redundant, #7 does this.
